### ISSUE TITLE
Redis cluster 튜토리얼 글 보고 질문 드립니다.

### ISSUE THREAD

**Issue by waterlove88** [haandol/haandol.github.com#2]
redis-cluster 구성 시 장애에 대해서는 어떻게 대응하는지 궁금합니다.

sentinel 을 구성하게 되면 master에 장애시점을 파악해 slave를 master로 승격 시키는 작업을 하는데

redis-cluster 구성 시 sentinel 이 필요없다 하셔서 이럴때 수동으로 대응해야하는지, 아니면 자동으로 진행하는지 만약 자동으로 진행한다면 어떻게 설정을 해줘야하는지 등을 알고 싶습니다.

**Comment by haandol** [comment]
앗 블로그를 방치해서 1월 글을 이제 보았군요...

아래 글을 참조하시면 구조를 이해하시기 쉬울 겁니다.
http://redisgate.kr/redis/cluster/cluster_introduction.php

redis 는 mesh 형태의 네트워크로 되어 있고  마스터가 죽으면,
자동으로 해당 마스터의 복제본(slave == replica) 을 마스터로 승격 시킵니다.
원래 이 역할을 센티널이 해줬는데 이제는 그냥 클러스터로 구성된 레디스 노드들이 알아서 합니다.

다만 커버리지가 깨졌을 경우 (즉, split-brain 현상이 일어나서 어떤 데이터가 원본인지 알 수 없게 될 수 있는 상태)
클러스터를 유지할 것인지 아니면 적절한 상태가 될 때 까지 클러스터를 셧다운 할 것인지 설정 해둘 수 있습니다. 

아래 글에서 좀 더 자세한 내용을 보실 수 있습니다.
http://redisgate.kr/redis/cluster/cluster_failover.php
http://redisgate.kr/redis/cluster/cluster-require-full-coverage.php
